CHORD_OPEN = '['
CHORD_CLOSE = ']'
CHORD_DURATION_SEPARATOR = ':'

DURATION_UNIT_MEASURE = 'm'
DURATION_UNIT_BEAT = 'b'
DURATION_UNIT_HALFBEAT = 'h'

BAR_SINGLE = '&#119040;'
BAR_DOUBLE = '&#119041;'
BAR_SECTION_OPEN = '&#119043;'
BAR_SECTION_CLOSE = '&#119042;'
BAR_REPEAT_OPEN = '&#119046;'
BAR_REPEAT_CLOSE = '&#119047;'

GROUP_REPEAT_OPEN = '{'
GROUP_REPEAT_CLOSE = '}'
GROUP_SUFFIX_OPEN = '('
GROUP_SUFFIX_CLOSE = ')'

ARG_ROW_BREAK = '/'

FILENAME_SUFFIX_COMBINED = 'combined'
FILENAME_SUFFIX_NO_LYRICS = 'leadsheet'
FILENAME_SUFFIX_LYRICS_ONLY = 'lyrics'

HTML_OUTPUT_SUBDIR = 'html'
PDF_OUTPUT_SUBDIR = 'pdf'
